# Generated by Django 2.2.6 on 2021-01-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210106_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Ваш комментарий', max_length=500),
        ),
    ]
